# Generated by Django 6.0.3 on 2026-03-25 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excavations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excavation_owner', to='users.user')),
                ('users', models.ManyToManyField(to='users.user')),
            ],
            options={
                'db_table': 'excavations',
            },
        ),
    ]
