# Generated by Django 6.0.4 on 2026-05-06 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excavations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='excavations',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_excavations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excavations',
            name='users',
            field=models.ManyToManyField(related_name='participating_excavations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('excavation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='excavations.excavations')),
            ],
            options={
                'db_table': 'sectors',
            },
        ),
    ]
