# Generated by Django 5.0 on 2026-03-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('surname2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.usertype')),
            ],
        ),
    ]
